// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package probe

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type trafficAddr struct {
	_ structs.HostLayout
	B [16]uint8
}

type trafficCounters struct {
	_         structs.HostLayout
	RxBytes   uint64
	RxPackets uint64
	TxBytes   uint64
	TxPackets uint64
}

type trafficLpmKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      [16]uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	trafficMapLocalNets = "local_nets"
	trafficMapStats     = "stats"
	trafficProgEgress   = "egress"
	trafficProgIngress  = "ingress"
	trafficVarL2Len     = "l2_len"
)

// loadTraffic returns the embedded CollectionSpec for traffic.
func loadTraffic() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TrafficBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load traffic: %w", err)
	}

	return spec, err
}

// loadTrafficObjects loads traffic and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*trafficObjects
//	*trafficPrograms
//	*trafficMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTrafficObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadTraffic()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// trafficSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type trafficSpecs struct {
	trafficProgramSpecs
	trafficMapSpecs
	trafficVariableSpecs
}

// trafficProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type trafficProgramSpecs struct {
	Egress  *ebpf.ProgramSpec `ebpf:"egress"`
	Ingress *ebpf.ProgramSpec `ebpf:"ingress"`
}

// trafficMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type trafficMapSpecs struct {
	LocalNets *ebpf.MapSpec `ebpf:"local_nets"`
	Stats     *ebpf.MapSpec `ebpf:"stats"`
}

// trafficVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type trafficVariableSpecs struct {
	L2Len *ebpf.VariableSpec `ebpf:"l2_len"`
}

// trafficObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTrafficObjects or ebpf.CollectionSpec.LoadAndAssign.
type trafficObjects struct {
	trafficPrograms
	trafficMaps
	trafficVariables
}

func (o *trafficObjects) Close() error {
	return _TrafficClose(
		&o.trafficPrograms,
		&o.trafficMaps,
	)
}

// trafficMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTrafficObjects or ebpf.CollectionSpec.LoadAndAssign.
type trafficMaps struct {
	LocalNets *ebpf.Map `ebpf:"local_nets"`
	Stats     *ebpf.Map `ebpf:"stats"`
}

func (m *trafficMaps) Close() error {
	return _TrafficClose(
		m.LocalNets,
		m.Stats,
	)
}

// trafficVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTrafficObjects or ebpf.CollectionSpec.LoadAndAssign.
type trafficVariables struct {
	L2Len *ebpf.Variable `ebpf:"l2_len"`
}

// trafficPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTrafficObjects or ebpf.CollectionSpec.LoadAndAssign.
type trafficPrograms struct {
	Egress  *ebpf.Program `ebpf:"egress"`
	Ingress *ebpf.Program `ebpf:"ingress"`
}

func (p *trafficPrograms) Close() error {
	return _TrafficClose(
		p.Egress,
		p.Ingress,
	)
}

func _TrafficClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed traffic_bpfel.o
var _TrafficBytes []byte
